plugins {
    alias(libs.plugins.android.application)
    id("org.lsposed.lsparanoid")
}

android {
    namespace = 'com.bewil.besms'
    compileSdk = 35

    sourceSets{
        main{
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }

    packagingOptions{
        jniLibs{
            useLegacyPackaging = true
        }
    }

    aaptOptions{
        noCompress "so"
    }

    defaultConfig {
        buildConfigField "String", "COMMIT_HASH", "\"${System.getenv("COMMIT_HASH") ?: "unknown"}\""
        buildConfigField "String", "UPDATE_FILE_NAME", "\"BeSMS.apk\""
        applicationId "com.bewil.besms"
        minSdk = 33
        targetSdk = 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            setMinifyEnabled(true)
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            setMinifyEnabled(false)
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    buildFeatures {
        viewBinding = true
        buildConfig = true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
}