name: Android CI

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set commit hash env variable
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Build with Gradle
      run: ./gradlew :app:assembleDebug
    - name: Generate file name env var
      run: |
          DATE=$(date +'%d.%m.%Y.%H.%M')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          MESSAGE=$(cat << EOF
          BeSMS-${DATE}-${COMMIT_HASH}
          EOF)
          echo OUTPUT_NAME=$MESSAGE >> $GITHUB_ENV
    - name: Rename APK
      run: mv "./app/build/outputs/apk/debug/app-debug.apk" "./app/build/outputs/apk/debug/${{ env.OUTPUT_NAME }}.apk"
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.OUTPUT_NAME }}.apk"
        path: "./app/build/outputs/apk/debug/${{ env.OUTPUT_NAME }}.apk"
